#!/usr/bin/python3
""" Fabric script that generates a .tgz archive  and distributes it
to server """
from fabric.api import put, run, sudo, local
from datetime import datetime
import os


def do_pack():
    """ generates a .tgz archive from the contents of the web_static folder
    of your AirBnB Clone repo, using the function do_pack."""

    t = datetime.now().strftime("%Y%m%d%H%M%S")
    name = "web_static_{}.tgz".format(t)
    local("mkdir -p versions")
    com = local(f"tar -cvzf versions/{name} web_static")

    if com.failed is True:
        return (None)
    return (f"versions/{name}")

def do_deploy(archive_path):
    """ distributes an archive to your web servers """
    if not os.path.exsist(archive_path):
        return(False)

    put(local_path=archive_path, remote_path="/tmp")
    file1 = archive_path.split("/")[1].split(".")[0]
    path = "/data/web_static/releases/{}".format(file1)
    sudo(f"mkdir -p {path}")
    sudo(f"tar -xzf /tmp/{file1}.tgz -C {path}")
    sudo(f"rm -rf /tmp/{name}")
    sudo(f"mv {path}/web_static/* {path}")
    sudo(f"ln -sf {path} /data/web_static/current")
